/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 26/11/2020 05:47:41
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     180000000
#define MX_SYSCLKFreq_VALUE                     180000000
#define MX_HCLKFreq_Value                       180000000
#define MX_FCLKCortexFreq_Value                 180000000
#define MX_CortexFreq_Value                     180000000
#define MX_AHBFreq_Value                        180000000
#define MX_APB1Freq_Value                       45000000
#define MX_APB2Freq_Value                       90000000
#define MX_APB1TimFreq_Value                    90000000
#define MX_APB2TimFreq_Value                    180000000
#define MX_48MHZClocksFreq_Value                90000000
#define MX_EthernetFreq_Value                   180000000
#define MX_LCDTFTFreq_Value                     12250000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_SAI_AClocksFreq_Value                12250000
#define MX_SAI_BClocksFreq_Value                12250000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    180000000

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream7_IRQn */
#define MX_DMA1_Stream7_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream7_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream7_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* DMA Configuration */

/* DMA I2C1_RX */
#define MX_I2C1_RX_DMA_DMA_Handle
#define MX_I2C1_RX_DMA_Instance                 DMA1_Stream0
#define MX_I2C1_RX_DMA_FIFOMode                 DMA_FIFOMODE_DISABLE
#define MX_I2C1_RX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_I2C1_RX_DMA_Channel                  DMA_CHANNEL_1
#define MX_I2C1_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_BYTE
#define MX_I2C1_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_BYTE
#define MX_I2C1_RX_DMA_Mode                     DMA_NORMAL
#define MX_I2C1_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_I2C1_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_I2C1_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_I2C1_RX_DMA_IpInstance

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM3_IRQn */
#define MX_TIM3_IRQn_interruptPremptionPriority 1
#define MX_TIM3_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM3_IRQn_Subriority                 0

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM4_IRQn */
#define MX_TIM4_IRQn_interruptPremptionPriority 6
#define MX_TIM4_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM4_IRQn_Subriority                 0

/*-------------------------------- UART5      --------------------------------*/

#define MX_UART5                                1

#define MX_UART5_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PC12 */
#define MX_UART5_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART5_TX_Pin                         PC12
#define MX_UART5_TX_GPIOx                       GPIOC
#define MX_UART5_TX_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_UART5_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART5_TX_GPIO_AF                     GPIO_AF8_UART5
#define MX_UART5_TX_GPIO_Mode                   GPIO_MODE_AF_OD

/* DMA Configuration */

/* DMA UART5_TX */
#define MX_UART5_TX_DMA_DMA_Handle
#define MX_UART5_TX_DMA_Instance                DMA1_Stream7
#define MX_UART5_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART5_TX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART5_TX_DMA_Channel                 DMA_CHANNEL_4
#define MX_UART5_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART5_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART5_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART5_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART5_TX_DMA_PeriphInc               DMA_PINC_DISABLE
#define MX_UART5_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART5_TX_DMA_IpInstance

/* NVIC Configuration */

/* NVIC UART5_IRQn */
#define MX_UART5_IRQn_interruptPremptionPriority 0
#define MX_UART5_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART5_IRQn_Subriority                0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB4 */
#define MX_PB4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB4_Pin                              PB4
#define MX_PB4_GPIOx                            GPIOB
#define MX_PB4_PinState                         GPIO_PIN_RESET
#define MX_PB4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB4_GPIO_Pin                         GPIO_PIN_4
#define MX_PB4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

